

name: VoxGenie
description: "A professional voice assistant application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.3.6

  # Routing
  go_router: ^10.2.0

  # Network & API
  http: ^1.1.0
  dio: ^5.3.2

  # Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Speech & Text
  flutter_tts: ^3.8.5
  speech_to_text: ^7.0.0

  # UI
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^5.1.0
  flutter_animate: ^4.1.1  # For animations
  flutter_screenutil: ^5.8.4
  glassmorphism_ui: ^0.3.0
  animated_text_kit: ^4.2.2
  simple_animations: ^5.0.2
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.5

  # aws_polly: ^1.0.2  # AWS Polly package
  # aws_common: ^1.0.0  # AWS common utilities
  # just_audio: ^0.9.34  # For playing audio streams
  # Others
  intl: ^0.19.0
  path_provider: ^2.1.5
  uuid: ^4.0.0
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  url_launcher: ^6.3.1
  connectivity_plus: ^4.0.2
  logger: ^2.0.1
  fl_chart: ^0.66.0
  record: ^6.0.0
  avatar_glow: ^3.0.1
  socket_io_client: ^3.1.2
  aws_polly: ^2.1.1
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1  # use latest

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/main_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/